from app.models import db, Group_Member, environment, SCHEMA
from sqlalchemy.sql import text

def seed_group_members():
    demo = Group_Member(user_id=1, group_id=1)
    marnie = Group_Member(user_id=2, group_id=1)
    bobbie = Group_Member(user_id=3, group_id=1)
    Bruno = Group_Member(user_id=4, group_id=1)
    Laila = Group_Member(user_id=5, group_id=1)
    Gojo = Group_Member(user_id=6, group_id=2)
    Killua = Group_Member(user_id=7, group_id=2)
    Sebastian = Group_Member(user_id=8, group_id=2)
    Yami = Group_Member(user_id=9, group_id=2)
    Naruto = Group_Member(user_id=10, group_id=2)
    Meredith = Group_Member(user_id=11, group_id=3)
    Derek = Group_Member(user_id=12, group_id=3)
    Alex = Group_Member(user_id=13, group_id=3)
    Cristina = Group_Member(user_id=14, group_id=3)
    Mark = Group_Member(user_id=15, group_id=3)
    George = Group_Member(user_id=16, group_id=3)
    Jonathan = Group_Member(user_id=20, group_id=4)
    Micheal = Group_Member(user_id=21, group_id=5)
    Celeste = Group_Member(user_id=22, group_id=6)
    Natalie = Group_Member(user_id=23, group_id=7)
    William = Group_Member(user_id=24, group_id=8)
    Anthony = Group_Member(user_id=25, group_id=9)
    Joshua = Group_Member(user_id=26, group_id=10)
    Ethan = Group_Member(user_id=27, group_id=11)
    Kayla = Group_Member(user_id=28, group_id=12)
    Kailee = Group_Member(user_id=29, group_id=4)
    Syliva = Group_Member(user_id=30, group_id=5)
    Abel = Group_Member(user_id=31, group_id=6)
    Mohammed = Group_Member(user_id=32, group_id=7)
    Kyle = Group_Member(user_id=33, group_id=8)
    Cole = Group_Member(user_id=34, group_id=9)
    Kai = Group_Member(user_id=35, group_id=10)
    Zane = Group_Member(user_id=36, group_id=11)
    Mary = Group_Member(user_id=37, group_id=12)

    db.session.add(demo)
    db.session.add(marnie)
    db.session.add(bobbie)
    db.session.add(Bruno)
    db.session.add(Laila)
    db.session.add(Gojo)
    db.session.add(Killua)
    db.session.add(Sebastian)
    db.session.add(Yami)
    db.session.add(Naruto)
    db.session.add(Meredith)
    db.session.add(Derek)
    db.session.add(Alex)
    db.session.add(Cristina)
    db.session.add(Mark)
    db.session.add(George)
    db.session.add(Jonathan)
    db.session.add(Micheal)
    db.session.add(Celeste)
    db.session.add(Natalie)
    db.session.add(William)
    db.session.add(Anthony)
    db.session.add(Joshua)
    db.session.add(Ethan)
    db.session.add(Kayla)
    db.session.add(Kailee)
    db.session.add(Syliva)
    db.session.add(Abel)
    db.session.add(Mohammed)
    db.session.add(Kyle)
    db.session.add(Cole)
    db.session.add(Kai)
    db.session.add(Zane)
    db.session.add(Mary)

    db.session.commit()



def undo_group_members():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.group_members RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM group_members"))

    db.session.commit()
